
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 0.9
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

#[colors]
#draw_bold_text_with_bright_colors = true

#[[colors.indexed_colors]]
#color = "0xF8BD96"
#index = 16

#[[colors.indexed_colors]]
#color = "0xF5E0DC"
#index = 17

#[colors.bright]
#black = "0x988BA2"
#blue = "0x96CDFB"
#cyan = "0x89DCEB"
#green = "0xABE9B3"
#magenta = "0xF5C2E7"
#red = "0xF28FAD"
#white = "0xD9E0EE"
#yellow = "0xFAE3B0"

#[colors.cursor]
#cursor = "0xF5E0DC"
#text = "0x1E1D2F"

#[colors.normal]
#black = "0x6E6C7E"
#blue = "0x96CDFB"
#cyan = "0x89DCEB"
#green = "0xABE9B3"
#magenta = "0xF5C2E7"
#red = "0xF28FAD"
#white = "0xD9E0EE"
#yellow = "0xFAE3B0"

#[colors.primary]
#background = "0x1E1D2F"
#foreground = "0xD9E0EE"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]

live_config_reload = true
working_directory = "None"
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/tokyonight_day.toml"
  # "~/.config/alacritty/tokyonight_moon.toml"
  # "~/.config/alacritty/tokyonight_night.toml"
  # "~/.config/alacritty/tokyonight_storm.toml"
]
